Interactive list
MuhmmdUsama/To-Do-List pull request #3
Opened 2022-07-15 19:24 UTC by MuhmmdUsama

- Update items object's value for completed key upon user actions.
- Implement a function for the "Clear all completed" button.
- Store the updated array of items in local storage.

2022-07-15 20:07 UTC, Gambit142 requested changes
Hi @MuhmmdUsama 👋, 

Good job so far!

## Highlights
- All linters checks passed ✔️ 
- README.md file is professional ✔️ 
- The ClearAll Completed button function properly ✔️ 

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
#### I am making this comment because I can not highlight the relevant code in the files changes section of this pull request. 👍 

- [x] Kindly move the piece of code that is responsible for changing the status of a task (`task.completed` to `true/false`) to a **_new file/module_**. 👍 

- [ ]  _Kindly check the comments under the review for other required changes._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider adding this command `npm install` as part of the instructions in the getting started section of your _**README.md**_. You can add it after the command for cloning and changing the directory to this folder. 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-07-16 15:44 UTC, MuhmmdUsama commented on src/action.js
> +    });
Hi, @Gambit142 
thanks for mentioning that, as I saw it's not a part of the project requirement for this section but I tried many times to update the index but still not updated, I took your advice but still not updated, there is something I missed, I will try figure what is it and create a clean version of my project

2022-07-16 16:04 UTC, mwanawabangona approved these changes
Hi @MuhmmdUsama ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

2022-07-16 16:24 UTC, merged

2022-07-16 16:50 UTC, Gambit142 commented on src/action.js
> +    });
Hi, @MuhmmdUsama, I understand that it isn't implicitly stated but remember in the add and remove a task, your index had to be rearranged after deleting a single task. It will be incoherent and inconsistent if you do not apply the same logic after deleting all the completed tasks on your to-do list. 👍